### ISSUE TITLE
feat: Testing

### ISSUE THREAD

**Issue by theS1LV3R** [CTFNote/backend#5]
**Is your feature request related to a problem? Please describe.**
When developing, its easy to miss bugs and errors.

**Describe the solution you'd like**
Add tests and stuff for components + routes

**Describe alternatives you've considered**
There tecnically aren't any alternatives to testing except for *not* testing

**Additional context**
https://dev.to/nedsoft/testing-nodejs-express-api-with-jest-and-supertest-1km6

**Comment by ent3r** [comment]
An issue has been created on Linear to track this issue: https://linear.app/ctfnote/issue/BACK-17/unit-testing
