### ISSUE TITLE
feat: CTF routes and services

### ISSUE THREAD

**Issue by theS1LV3R** [CTFNote/backend#6]
All routes and services involved with handling CTF management. E.g. editing ctf details, creating new ctfs, updating participants, etc.

1. Create the service that will handle everything
  - [ ] Create new CTF
  - [ ] Get CTF details
  - [ ] Update CTF details
  - [ ] Update participants
  - [ ] (Un)Archive CTF
  - [ ] Export CTF to JSON file
  - [ ] Create new CTF from json file

2. Create routes for everything
  - [ ] `POST {{apiURL}}/ctf`. Create new CTF
  - [ ] `PATCH {{apiURL}}/ctf/:ctfID`. Update CTF details
  - [ ] `GET {{apiURL}}/ctf`. Get CTF details
  - (more to come)

**Comment by ent3r** [comment]
Issue has been created on linear: https://linear.app/ctfnote/issue/BACK-27
